name: Build and Push Docker Build Image

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to build the Docker image from'
        required: true
        default: 'main'
      tag:
        description: 'Docker tag for the image'
        required: true
        default: 'latest'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build Docker image
      run: |
        docker build -t ghcr.io/${{ github.repository }}/dotnet-godot:${{ github.event.inputs.tag }} .

    - name: Push Docker image
      run: |
        docker push ghcr.io/${{ github.repository }}/dotnet-godot:${{ github.event.inputs.tag }}

    - name: Logout from Docker
      run: |
        docker logout ghcr.io
